import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

//Website Page
import { Navbar } from "../components/Navbar";
import { Mantra } from "../components/Mantra";
import { AboutMe } from "../components/AboutMe";
import { Skills } from "../components/Skills";
import { Projects } from "../components/Projects";
import { Contact } from "../components/Contact";
import { Footer } from "../components/Footer";
import { Experience } from "../components/Experience";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Wen Hao | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/wenhaologo.png" />
      </Head>

      <Navbar />
      <Mantra />
      <AboutMe />
      <Skills />
      <Experience />
      <Projects />
      <Contact />
      <Footer />
    </>
  );
}
